/**
 * Standardized error codes for API responses
 */
export const ErrorCodes = {
  // Authentication errors
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  MFA_REQUIRED: 'MFA_REQUIRED',
  MFA_INVALID: 'MFA_INVALID',

  // Validation errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',

  // Resource errors
  NOT_FOUND: 'NOT_FOUND',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  LIST_NOT_FOUND: 'LIST_NOT_FOUND',
  LABEL_NOT_FOUND: 'LABEL_NOT_FOUND',

  // Conflict errors
  CONFLICT: 'CONFLICT',
  DUPLICATE: 'DUPLICATE',
  CIRCULAR_DEPENDENCY: 'CIRCULAR_DEPENDENCY',

  // Rate limiting
  RATE_LIMITED: 'RATE_LIMITED',

  // Server errors
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  IMPORT_ERROR: 'IMPORT_ERROR',
  EXPORT_ERROR: 'EXPORT_ERROR',

  // Business logic errors
  CANNOT_COMPLETE: 'CANNOT_COMPLETE',
  INVALID_OPERATION: 'INVALID_OPERATION',
  INVALID_REQUEST: 'INVALID_REQUEST',
  MAX_RECURRANCE_REACHED: 'MAX_RECURRANCE_REACHED',
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];