import { group } from 'k6';
import http from 'k6/http';
import { check } from 'k6';
import { sleep } from 'k6';

// Performance test for the Task API
export const options = {
  stages: [
    { duration: '30s', target: 50 },   // ramp-up to 50 users
    { duration: '1m', target: 50 },    // stay at 50 users
    { duration: '30s', target: 0 },    // ramp-down
  ],
  thresholds: {
    'http_req_duration': ['p(95)<1000'], // 95% of requests must be under 1s
    'checks': ['rate>=0.9'],             // 90% of checks must pass
  },
};

export default function () {
  // Simulate creating a task
  group('Create Task', () => {
    const payload = {
      title: 'Load Test Task',
      description: 'Generated by k6',
      status: 'pending',
    };
    const res = http.post('http://localhost:3000/api/tasks', JSON.stringify(payload), {
      headers: { 'Content-Type': 'application/json' },
    });
    check(res, {
      'status was 201': (r) => r.status === 201,
      'response contains createdAt': (r) => r.body && r.body.createdAt,
    });
    sleep(1);
  });

  // Simulate fetching tasks
  group('Read Tasks', () => {
    const res = http.get('http://localhost:3000/api/tasks');
    check(res, {
      'status was 200': (r) => r.status === 200,
      'response is JSON': (r) => r.headers['Content-Type'] === 'application/json',
    });
    sleep(1);
  });

  // Simulate updating a task
  group('Update Task', () => {
    const taskId = '12345'; // static id for the test
    const payload = {
      status: 'completed',
    };
    const res = http.put(`http://localhost:3000/api/tasks/${taskId}`, JSON.stringify(payload), {
      headers: { 'Content-Type': 'application/json' },
    });
    check(res, {
      'status was 200': (r) => r.status === 200,
    });
    sleep(1);
  });
}